<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/06 09:30:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bestyolo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
